image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

pages:
  script:
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master


